line-length = 100
target-version = "py312"
exclude = ["alembic"]

[lint]
select = ["E", "F", "I", "B", "UP"]

# formatはデフォルトで十分なので指定しない

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.File"]
